from typing import Annotated

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]


class GrainAgentState(MessagesState):
    """Commodity-specific state with unambiguous contract semantics."""

    asset_type: Annotated[str, "Always commodity_future for GrainAgents runs"]
    commodity: Annotated[str, "Normalized commodity name"]
    contract_symbol: Annotated[str, "Delivery-specific futures contract"]
    crop_year: Annotated[str, "Crop-marketing year, for example 2026/27"]
    analysis_date: Annotated[str, "Point-in-time analysis date"]
    trade_date: Annotated[str, "Compatibility alias for analysis_date"]
    forecast_horizons: Annotated[list[int], "Trading-day forecast horizons"]
    evidence_package_uri: Annotated[str, "Immutable evidence package location"]
    instrument_context: Annotated[str, "Deterministic contract identity"]
    company_of_interest: Annotated[str, "Compatibility alias for contract_symbol"]
    sender: Annotated[str, "Agent that sent the latest message"]

    market_report: Annotated[str, "Compatibility alias for the technical report"]
    technical_report: Annotated[str, "Technical and futures-contract report"]
    supply_demand_report: Annotated[str, "Supply-and-demand report"]
    weather_report: Annotated[str, "Weather-and-yield report"]
    demand_report: Annotated[str, "Export and domestic demand report"]
    positioning_report: Annotated[str, "Positioning and sentiment report"]
    news_report: Annotated[str, "Grain news and macro report"]
    quantitative_forecast_report: Annotated[str, "Deterministic forecast explanation"]
    bull_case: Annotated[str, "Evidence-linked bull case"]
    bear_case: Annotated[str, "Evidence-linked bear case"]
    scenario_report: Annotated[str, "Probability-constrained scenarios"]
    risk_report: Annotated[str, "Commodity risk review"]
    final_outlook: Annotated[str, "Final market outlook"]
    newsletter_draft: Annotated[str, "Human-review newsletter draft"]
